POST http://localhost:3333/videos
Content-type: application/json

{
    "title": "other videoooo",
    "description": "daleeeeeeee gremio.",
    "duration": 180
}

###

GET  http://localhost:3333/videos


###

PUT http://localhost:3333/videos/be8a8f41-4db1-4fbb-992d-678c364c7265
Content-type: application/json

{
    "title": "My FUCKING VIDEO motherfucker!",
    "description": "This is a description of my first video.",
    "duration": 180
}

###

DELETE http://localhost:3333/videos/be8a8f41-4db1-4fbb-992d-678c364c7265